//! Upgrade stat types and per-category upgrade tables.

/// Resource types used in upgrade costs.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum ResourceKind {
    Food,
    Gold,
}

/// Which stat an upgrade improves.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum UpgradeStatKind {
    // Core NPC stats
    Hp,
    Attack,
    Range,
    AttackSpeed,
    MoveSpeed,
    Stamina,
    // Special NPC stats
    Yield,
    Alert,
    Dodge,
    ProjectileSpeed,
    ProjectileLifetime,
    HpRegen,
    // Town-only stats (not NPC-driven)
    Healing,
    FountainRange,
    FountainAttackSpeed,
    FountainProjectileLife,
    Expansion,
    // Building unlocks
    UnlockStoneRoad,
    UnlockMetalRoad,
}

/// How an upgrade's effect is displayed in the UI.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum EffectDisplay {
    /// +X% per level (standard multiplicative)
    Percentage,
    /// +X% speed boost (reciprocal: 1/(1+n*pct), displayed as positive)
    CooldownReduction,
    /// Binary unlock (level 0 = locked, level 1+ = unlocked)
    Unlock,
    /// +Npx per level (flat additive, displayed as pixels)
    FlatPixels(i32),
    /// +N per level (discrete integer)
    Discrete,
}

/// One upgradeable stat declaration on an NPC category.
#[derive(Clone, Copy, Debug)]
pub struct UpgradeStatDef {
    pub kind: UpgradeStatKind,
    pub pct: f32,
    pub cost: &'static [(ResourceKind, i32)],
    pub label: &'static str,
    pub short: &'static str,
    pub tooltip: &'static str,
    pub display: EffectDisplay,
    /// Prerequisite: another stat in the same category that must be at min_level.
    pub prereq_stat: Option<UpgradeStatKind>,
    pub prereq_level: u8,
    /// Whether this upgrade triggers NPC stat re-resolution.
    pub is_combat_stat: bool,
    /// Whether purchasing this triggers healing zone invalidation.
    pub invalidates_healing: bool,
    /// Whether purchasing this triggers town grid expansion.
    pub triggers_expansion: bool,
    /// Custom cost function instead of standard exponential scaling.
    pub custom_cost: bool,
    /// Max level cap (None = unlimited, capped by cost growth at ~20).
    pub max_level: Option<u8>,
}

use ResourceKind::{Food as F, Gold as G};
use UpgradeStatKind as USK;

// Helper for concise UpgradeStatDef construction
const fn usd(
    kind: UpgradeStatKind,
    pct: f32,
    cost: &'static [(ResourceKind, i32)],
    label: &'static str,
    short: &'static str,
    tooltip: &'static str,
    display: EffectDisplay,
) -> UpgradeStatDef {
    UpgradeStatDef {
        kind,
        pct,
        cost,
        label,
        short,
        tooltip,
        display,
        prereq_stat: None,
        prereq_level: 1,
        is_combat_stat: true,
        invalidates_healing: false,
        triggers_expansion: false,
        custom_cost: false,
        max_level: None,
    }
}

const fn usd_noncombat(
    kind: UpgradeStatKind,
    pct: f32,
    cost: &'static [(ResourceKind, i32)],
    label: &'static str,
    short: &'static str,
    tooltip: &'static str,
    display: EffectDisplay,
) -> UpgradeStatDef {
    UpgradeStatDef {
        kind,
        pct,
        cost,
        label,
        short,
        tooltip,
        display,
        prereq_stat: None,
        prereq_level: 1,
        is_combat_stat: false,
        invalidates_healing: false,
        triggers_expansion: false,
        custom_cost: false,
        max_level: None,
    }
}

const fn usd_req(
    kind: UpgradeStatKind,
    pct: f32,
    cost: &'static [(ResourceKind, i32)],
    label: &'static str,
    short: &'static str,
    tooltip: &'static str,
    display: EffectDisplay,
    prereq: UpgradeStatKind,
    prereq_lv: u8,
) -> UpgradeStatDef {
    UpgradeStatDef {
        kind,
        pct,
        cost,
        label,
        short,
        tooltip,
        display,
        prereq_stat: Some(prereq),
        prereq_level: prereq_lv,
        is_combat_stat: true,
        invalidates_healing: false,
        triggers_expansion: false,
        custom_cost: false,
        max_level: None,
    }
}

// Military upgrade stat defs
pub(crate) const MILITARY_RANGED_UPGRADES: &[UpgradeStatDef] = &[
    usd(
        USK::Hp,
        0.10,
        &[(F, 1)],
        "HP",
        "HP",
        "+10% HP per level",
        EffectDisplay::Percentage,
    ),
    usd(
        USK::Attack,
        0.10,
        &[(F, 1)],
        "Attack",
        "Atk",
        "+10% damage per level",
        EffectDisplay::Percentage,
    ),
    usd(
        USK::Range,
        0.05,
        &[(G, 1)],
        "Detection Range",
        "Det",
        "+5% detection range per level",
        EffectDisplay::Percentage,
    ),
    usd(
        USK::AttackSpeed,
        0.08,
        &[(F, 1)],
        "Attack Speed",
        "AtkSpd",
        "+8% attack speed per level",
        EffectDisplay::CooldownReduction,
    ),
    usd(
        USK::MoveSpeed,
        0.05,
        &[(F, 1)],
        "Move Speed",
        "MvSpd",
        "+5% movement speed per level",
        EffectDisplay::Percentage,
    ),
    usd_req(
        USK::Alert,
        0.10,
        &[(G, 1)],
        "Alert",
        "Alert",
        "+10% alert radius per level",
        EffectDisplay::Percentage,
        USK::MoveSpeed,
        1,
    ),
    usd_req(
        USK::Stamina,
        0.10,
        &[(F, 1)],
        "Stamina",
        "Stam",
        "+10% stamina per level",
        EffectDisplay::CooldownReduction,
        USK::MoveSpeed,
        1,
    ),
    usd_req(
        USK::Dodge,
        0.0,
        &[(G, 20)],
        "Dodge",
        "Dodge",
        "Unlocks projectile dodging",
        EffectDisplay::Unlock,
        USK::MoveSpeed,
        5,
    ),
    usd(
        USK::ProjectileSpeed,
        0.08,
        &[(G, 1)],
        "Arrow Speed",
        "ASpd",
        "+8% arrow speed per level",
        EffectDisplay::Percentage,
    ),
    usd(
        USK::ProjectileLifetime,
        0.08,
        &[(G, 1)],
        "Arrow Range",
        "ARng",
        "+8% arrow flight distance per level",
        EffectDisplay::Percentage,
    ),
    usd_noncombat(
        USK::HpRegen,
        0.0,
        &[(G, 2)],
        "HP Regen",
        "Regen",
        "+0.5 HP/s passive regen per level",
        EffectDisplay::Discrete,
    ),
];

pub(crate) const MILITARY_MELEE_UPGRADES: &[UpgradeStatDef] = &[
    usd(
        USK::Hp,
        0.10,
        &[(F, 1)],
        "HP",
        "HP",
        "+10% HP per level",
        EffectDisplay::Percentage,
    ),
    usd(
        USK::Attack,
        0.10,
        &[(F, 1)],
        "Attack",
        "Atk",
        "+10% damage per level",
        EffectDisplay::Percentage,
    ),
    usd(
        USK::AttackSpeed,
        0.08,
        &[(F, 1)],
        "Attack Speed",
        "AtkSpd",
        "+8% attack speed per level",
        EffectDisplay::CooldownReduction,
    ),
    usd(
        USK::MoveSpeed,
        0.05,
        &[(F, 1)],
        "Move Speed",
        "MvSpd",
        "+5% movement speed per level",
        EffectDisplay::Percentage,
    ),
    usd_req(
        USK::Alert,
        0.10,
        &[(G, 1)],
        "Alert",
        "Alert",
        "+10% alert radius per level",
        EffectDisplay::Percentage,
        USK::MoveSpeed,
        1,
    ),
    usd_req(
        USK::Stamina,
        0.10,
        &[(F, 1)],
        "Stamina",
        "Stam",
        "+10% stamina per level",
        EffectDisplay::CooldownReduction,
        USK::MoveSpeed,
        1,
    ),
    usd_req(
        USK::Dodge,
        0.0,
        &[(G, 20)],
        "Dodge",
        "Dodge",
        "Unlocks projectile dodging",
        EffectDisplay::Unlock,
        USK::MoveSpeed,
        5,
    ),
    usd_noncombat(
        USK::HpRegen,
        0.0,
        &[(G, 2)],
        "HP Regen",
        "Regen",
        "+0.5 HP/s passive regen per level",
        EffectDisplay::Discrete,
    ),
];

pub(crate) const FARMER_UPGRADES: &[UpgradeStatDef] = &[
    usd(
        USK::Yield,
        0.15,
        &[(F, 1)],
        "Yield",
        "Yield",
        "+15% food production per level",
        EffectDisplay::Percentage,
    ),
    usd(
        USK::Hp,
        0.20,
        &[(F, 1)],
        "HP",
        "HP",
        "+20% farmer HP per level",
        EffectDisplay::Percentage,
    ),
    usd(
        USK::MoveSpeed,
        0.05,
        &[(F, 1)],
        "Move Speed",
        "MvSpd",
        "+5% farmer speed per level",
        EffectDisplay::Percentage,
    ),
    usd_req(
        USK::Stamina,
        0.10,
        &[(F, 1)],
        "Stamina",
        "Stam",
        "+10% stamina per level",
        EffectDisplay::CooldownReduction,
        USK::MoveSpeed,
        1,
    ),
];

pub(crate) const MINER_UPGRADES: &[UpgradeStatDef] = &[
    usd(
        USK::Hp,
        0.20,
        &[(F, 1)],
        "HP",
        "HP",
        "+20% miner HP per level",
        EffectDisplay::Percentage,
    ),
    usd(
        USK::MoveSpeed,
        0.05,
        &[(F, 1)],
        "Move Speed",
        "MvSpd",
        "+5% miner speed per level",
        EffectDisplay::Percentage,
    ),
    usd_req(
        USK::Stamina,
        0.10,
        &[(F, 1)],
        "Stamina",
        "Stam",
        "+10% stamina per level",
        EffectDisplay::CooldownReduction,
        USK::MoveSpeed,
        1,
    ),
    usd_noncombat(
        USK::Yield,
        0.15,
        &[(G, 1)],
        "Yield",
        "Yield",
        "+15% gold yield per level",
        EffectDisplay::Percentage,
    ),
];

/// Per-tower-instance upgrades (purchasable on each tower individually).
pub const TOWER_UPGRADES: &[UpgradeStatDef] = &[
    usd(
        USK::Hp,
        0.10,
        &[(F, 1)],
        "HP",
        "HP",
        "+10% tower HP per level",
        EffectDisplay::Percentage,
    ),
    usd(
        USK::Attack,
        0.10,
        &[(F, 1)],
        "Attack",
        "Atk",
        "+10% tower damage per level",
        EffectDisplay::Percentage,
    ),
    usd(
        USK::Range,
        0.05,
        &[(G, 1)],
        "Range",
        "Rng",
        "+5% tower range per level",
        EffectDisplay::Percentage,
    ),
    usd(
        USK::AttackSpeed,
        0.08,
        &[(F, 1)],
        "Attack Speed",
        "AtkSpd",
        "+8% tower attack speed per level",
        EffectDisplay::CooldownReduction,
    ),
    usd(
        USK::ProjectileSpeed,
        0.08,
        &[(G, 1)],
        "Proj Speed",
        "PSpd",
        "+8% projectile speed per level",
        EffectDisplay::Percentage,
    ),
    usd(
        USK::ProjectileLifetime,
        0.08,
        &[(G, 1)],
        "Proj Range",
        "PRng",
        "+8% projectile range per level",
        EffectDisplay::Percentage,
    ),
    usd_noncombat(
        USK::HpRegen,
        0.0,
        &[(G, 2)],
        "HP Regen",
        "Regen",
        "+2 HP/s passive regen per level",
        EffectDisplay::Discrete,
    ),
];

// Town upgrades (not NPC-driven, appended to registry as "Town" branch)
pub const TOWN_UPGRADES: &[UpgradeStatDef] = &[
    UpgradeStatDef {
        kind: USK::Healing,
        pct: 0.20,
        cost: &[(F, 1)],
        label: "Healing",
        short: "Heal",
        tooltip: "+20% HP regen at fountain",
        display: EffectDisplay::Percentage,
        prereq_stat: None,
        prereq_level: 1,
        is_combat_stat: false,
        invalidates_healing: true,
        triggers_expansion: false,
        custom_cost: false,
        max_level: None,
    },
    UpgradeStatDef {
        kind: USK::FountainRange,
        pct: 0.0,
        cost: &[(G, 1)],
        label: "Fountain Range",
        short: "FRng",
        tooltip: "+24px fountain range per level",
        display: EffectDisplay::FlatPixels(24),
        prereq_stat: Some(USK::Healing),
        prereq_level: 1,
        is_combat_stat: false,
        invalidates_healing: true,
        triggers_expansion: false,
        custom_cost: false,
        max_level: None,
    },
    UpgradeStatDef {
        kind: USK::FountainAttackSpeed,
        pct: 0.08,
        cost: &[(G, 1)],
        label: "Fountain Atk Speed",
        short: "FAS",
        tooltip: "+8% fountain attack speed per level",
        display: EffectDisplay::CooldownReduction,
        prereq_stat: Some(USK::FountainRange),
        prereq_level: 1,
        is_combat_stat: false,
        invalidates_healing: false,
        triggers_expansion: false,
        custom_cost: false,
        max_level: None,
    },
    UpgradeStatDef {
        kind: USK::FountainProjectileLife,
        pct: 0.08,
        cost: &[(G, 1)],
        label: "Fountain Proj Life",
        short: "FPL",
        tooltip: "+8% fountain projectile life per level",
        display: EffectDisplay::Percentage,
        prereq_stat: Some(USK::FountainRange),
        prereq_level: 1,
        is_combat_stat: false,
        invalidates_healing: false,
        triggers_expansion: false,
        custom_cost: false,
        max_level: None,
    },
    UpgradeStatDef {
        kind: USK::Expansion,
        pct: 0.0,
        cost: &[(F, 1), (G, 1)],
        label: "Expansion",
        short: "Area",
        tooltip: "+1 buildable radius per level",
        display: EffectDisplay::Discrete,
        prereq_stat: None,
        prereq_level: 1,
        is_combat_stat: false,
        invalidates_healing: false,
        triggers_expansion: true,
        custom_cost: true,
        max_level: None,
    },
    UpgradeStatDef {
        kind: USK::UnlockStoneRoad,
        pct: 0.0,
        cost: &[(F, 10), (G, 5)],
        label: "Stone Roads",
        short: "SRoad",
        tooltip: "Unlocks Stone Road (2x speed, +5 build radius)",
        display: EffectDisplay::Unlock,
        prereq_stat: None,
        prereq_level: 1,
        is_combat_stat: false,
        invalidates_healing: false,
        triggers_expansion: false,
        custom_cost: false,
        max_level: Some(1),
    },
    UpgradeStatDef {
        kind: USK::UnlockMetalRoad,
        pct: 0.0,
        cost: &[(F, 20), (G, 10)],
        label: "Metal Roads",
        short: "MRoad",
        tooltip: "Unlocks Metal Road (2.5x speed, +7 build radius)",
        display: EffectDisplay::Unlock,
        prereq_stat: Some(USK::UnlockStoneRoad),
        prereq_level: 1,
        is_combat_stat: false,
        invalidates_healing: false,
        triggers_expansion: false,
        custom_cost: false,
        max_level: Some(1),
    },
];
